# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pinp_char <- function(x, y) {
    .Call('_stRands_pinp_char', PACKAGE = 'stRands', x, y)
}

